executable            = /afs/cern.ch/user/p/pibutti/sw/condor_helpers/acts_test.sh
arguments             = 100 200 $(ClusterId) $(ProcId)
output                = jet_chain.$(ClusterId).$(ProcId).out
error                 = jet_chain.$(ClusterId).$(ProcId).err
log                   = jet_chain.$(ClusterId).$(ProcId).log
request_cpus   = 1
request_memory = 1024
request_disk   = 10240

+JobFlavour = "longlunch"

should_transfer_files = yes
queue 1000


