executable            = /afs/cern.ch/user/p/pibutti/sw/condor_helpers/sub_athena/athena_test.sh
arguments             = 1 2 $(ClusterId) $(ProcId)
output                = athena_test.$(ClusterId).$(ProcId).out
error                 = athena_test.$(ClusterId).$(ProcId).err
log                   = athena_test.$(ClusterId).$(ProcId).log
request_cpus   = 1
request_memory = 1024
request_disk   = 10240

+JobFlavour = "longlunch"

should_transfer_files = yes
queue 1


