executable            = /afs/cern.ch/user/p/pibutti/sw/condor_helpers/sub_athena/athena_IDPVM_inputfile.sh
arguments             = $(file) $(ClusterId) $(ProcId) DEFAULT
output                = /afs/cern.ch/user/p/pibutti/sw/condor_helpers/sub_athena/logs/athena_test.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/p/pibutti/sw/condor_helpers/sub_athena/logs/athena_test.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/p/pibutti/sw/condor_helpers/sub_athena/logs/athena_test.$(ClusterId).$(ProcId).log
request_cpus   = 4
#request_memory = 8096
#request_disk   = 20480

+JobFlavour = "longlunch"

should_transfer_files = yes
queue file from ./DEFAULT_ttbar200_xAOD_legacy/list.txt


